### ISSUE TITLE
Upload is completely broken because utils.slugify is removed in NodeBB 1.16

### ISSUE THREAD

**Issue by cra10** [NodeBB/nodebb-plugin-composer-quill#155]

**Comment by barisusakli** [comment]
Thanks for reporting fixed in 1.7.4

**Comment by cra10** [comment]
It's (partially) working after this update, but there's still a bug:

![image](https://user-images.githubusercontent.com/40766708/103178592-faeaea80-4838-11eb-9703-2b4ba91025c8.png)
![image](https://user-images.githubusercontent.com/40766708/103178595-0211f880-4839-11eb-8730-21f3c7ac46e8.png)

The images do upload and appear, but it stays at 0% in the bottom left corner

**Comment by barisusakli** [comment]
Published 1.7.5, the progress always shows 0% which seems to be a different issue https://github.com/NodeBB/NodeBB/issues/9151
