### ISSUE TITLE
Composer broken on NodeBB 1.16.1

### ISSUE THREAD

**Issue by sm2x** [NodeBB/nodebb-plugin-composer-quill#158]
nodebb-plugin-composer-quill   v1.7.6
NodeBB v1.16.1

Composer is unusable and console logs below error: 
![image](https://user-images.githubusercontent.com/6595333/104807104-226d1b80-5817-11eb-9bf0-e036ed365fde.png)

**Comment by barisusakli** [comment]
Please provide  reproduction steps.

**Comment by sm2x** [comment]
1.  install nodebb-plugin-composer-quill v1.7.6 from available Plugins
2.  enable composer-quill and disable:  
     - nodebb-plugin-composer-default
     - nodebb-plugin-markdown
3.  restart nodebb
4.  reply to an existing post, its not responding <-- Issue, then the above console logs appear

**Comment by barisusakli** [comment]
Did you rebuild nodebb after step 2? Seems like composer-default client side javascript is still executing and causing that error.

**Comment by sm2x** [comment]
thats it, thanks barisusakli, never thought that will be necessary
