### ISSUE TITLE
Reply does not format text as a quote

### ISSUE THREAD

**Issue by maciejbak85** [NodeBB/nodebb-plugin-composer-quill#193]
Hi,

I love your plugin, but there is one big issue that I have.
I have installed 2.2.1 version.

When I click reply button:

https://imgur.com/L14EAMU

in composer text is not marked as a quote

https://imgur.com/RQFXDtd

should be of course like here:

https://imgur.com/SeHTynY

thanks!

**Comment by julianlam** [comment]
v2.2.5, thanks!
