### ISSUE TITLE
not work in nodebb v1.10.2

### ISSUE THREAD

**Issue by BluesVN** [NodeBB/nodebb-plugin-composer-quill#196]
not work in nodebb v1.10.2

**Comment by julianlam** [comment]
Hi there, v1.10.2 is very very old, please upgrade to the latest version of NodeBB.

**Comment by BluesVN** [comment]
The new version has compatibility issues with the dingTalk browser, so I had to downgrade TT

**Comment by BluesVN** [comment]
The new version has compatibility issues with the dingTalk browser, so I had to downgrade . TT

v1.17.2 to v1.14 to v.1.10.2;
ES syntax causes incompatibility between the login module and some Android phones.
