### ISSUE TITLE
how to convert existing posts?

### ISSUE THREAD

**Issue by persevereVon** [NodeBB/nodebb-plugin-composer-quill#24]
> Warning This composer saves its data in a unique format that is only compatible with Quill. You'll have to use the bundled importer/exporter to convert existing posts if necessary.

can u tell me where is the importer/exporter tool? I can't find it. thank you.

**Comment by julianlam** [comment]
Ah this might no longer be an issue, as Quill saves in that unique format only for itself (now), and outputs HTML for intercompatibility with other composers.
