### ISSUE TITLE
Invalid event : plugins.composer.getFormattingOptions

### ISSUE THREAD

**Issue by HerrUU** [NodeBB/nodebb-plugin-composer-quill#247]
Just installed this plugin. No errors on installing but when I try to create a topic or post a reply, I get this error : 
![image](https://user-images.githubusercontent.com/45530805/143766129-f205f1d7-aa50-4897-9ad7-9175284b0012.png)

Can you help?

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-composer-quill/issues/246
