### ISSUE TITLE
Resize image in client

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-composer-quill#27]
Hi @julianlam ,
I believe we should resize uploaded images in the client, saving server CPU time and bandwidth.
To accomplish, lets call upload.show() instead of sending the file directly to /api/... 
In upload.show, we may implement resizing. 
Hope that's acceptable.
JJ,

**Comment by julianlam** [comment]
We don't proactively resize images on the client-side because it's advantageous to keep the original image to resize in the future if needed.

Also, some photography forums definitely don't like having their images resized :smile:

**Comment by PostMidnight** [comment]
I totally understand. Will you consider making this configurable?
As a last resort, will you consider calling upload.js so it may be modified separately from quill?
