### ISSUE TITLE
The new message button no longer works.

### ISSUE THREAD

**Issue by esenjin** [NodeBB/nodebb-plugin-composer-quill#34]
Good evening,
I have a problem on my forum with the module, when I click on the "new message"/ "reply" button, nothing happens. As if the button didn't exist.

Do you know where this problem comes from? 

I downloaded the MASTER archive that I decompressed and sent to my server, then installed the module, taking care to disable all other compositers and BBcodes modules. I have the latest version of NodeBBB (1.12.1)

Here is a short video that shows this:

[http://concepts.esenjin.xyz/cyla/v2/file/D57D3C.mp4](url)

Thanks !

**Comment by julianlam** [comment]
Hello @esenjin -- when you installed and activated the module, did you also run `./nodebb build` before restarting NodeBB?

**Comment by esenjin** [comment]
I have this error when running the command : 

```2019-05-06T19:59:07.269Z [undefined/11851] - warn: [meta/css] File not found! nodebb-plugin-composer-quill/node_modules/quill/dist/quill.snow.css
2019-05-06T19:59:07.269Z [undefined/11851] - warn: [meta/css] File not found! nodebb-plugin-composer-quill/node_modules/quill/dist/quill.bubble.css
2019-05-06T19:59:07.339Z [undefined/11851] - warn: [meta/css] File not found! nodebb-plugin-composer-quill/node_modules/quill/dist/quill.snow.css
2019-05-06T19:59:07.339Z [undefined/11851] - warn: [meta/css] File not found! nodebb-plugin-composer-quill/node_modules/quill/dist/quill.bubble.css
```

**Comment by julianlam** [comment]
Ah, I see. It looks like you maybe did not run `npm i` or `yarn` from within the unzipped archive.

**Comment by esenjin** [comment]
Aaaaah, I'm stupid, that's just it T_T
Thank you very much and sorry to have disturbed for so little...

**Comment by julianlam** [comment]
No problem, I am glad to assist :smile:
