### ISSUE TITLE
How to add a url?

### ISSUE THREAD

**Issue by esenjin** [NodeBB/nodebb-plugin-composer-quill#35]
Hello,

Sorry, I'll be back with a new problem. There is no button to add a hypertext link, whereas we can see that there is a tool for this, when we copy/paste a link.

![ql-tooltip](https://user-images.githubusercontent.com/41757656/57698019-d7b7fb00-7654-11e9-9905-e2faed828835.png)

I thought it might have been an option to check in the administration panel, but it is impossible to access the page `/admin/plugins/composer-quill`

![ql-admin](https://user-images.githubusercontent.com/41757656/57698080-fae2aa80-7654-11e9-90aa-658dd00aaf12.png)

I wish you can help me.

**Comment by julianlam** [comment]
That's a little odd, about the admin page not showing up. Can you try `./nodebb build tpl` and see if the page becomes accessible then?

**Comment by esenjin** [comment]
I wait for my administrator to come home and I see that. What about the button for hyperlinks?
