### ISSUE TITLE
Emojis 

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-composer-quill#63]
Hi @julianlam, @pitaj,

Emoji's dialog box will be displayed only when this fix is done on the emoji plugin:
https://github.com/NodeBB/nodebb-plugin-emoji/issues/29#issue-471623468

However, once the fix is done, and an emoji is selected from the dialog box, we hit the following issue:
Uncaught TypeError: t.context.getSelection is not a function

In this function:
quill-nbb.js
```
$(window).on('action:composer.insertIntoTextarea', function (evt, data) {
		var selection = data.context.getSelection(true);
		data.context.insertText(selection.index, data.value);
		data.preventDefault = true;
	});
```

Looks like data.context has the following functions declared:
getBlockData: ƒ (e,t,n)
insertIntoTextarea: ƒ (t,n)
updateTextareaSelection: ƒ (e,t,n)
wrapSelectionInTextareaWith:

I also looked at emoji plugin and found out that it does not exports getSelection, perhaps it should?

As for data.context.insertText(selection.index, data.value); 
perhaps you wanted to call data.context.insertIntoTextarea instead?

**Comment by julianlam** [comment]
https://github.com/NodeBB/nodebb-plugin-emoji/issues/29
