### ISSUE TITLE
Chat: Empty messages are sent to the server

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-composer-quill#69]
Hi @julianlam 

Apology for the number of issues filed recently ;) 

Another one surfaced: Following the very first chat message, quill will insert '\n' at the end of each subsequent message, even if the text window is clear.

We can eliminate empty messages with the below code, inserted into public/src/chats/messages.js right after if(!msg.trim().length).

Note I could have compared msg with specific string, such as: {"ops":[{"insert":"\n\"}]}. Unfortunately, it turns out that attributes are added as well, for example, in RTL the string will look like this: {"ops":[{"attributes":{"direction":"rtl","align":"right"},"insert":"\n"}]}. Since the plugin needs to support multiple configurations, parsing JSON is probably a better choice.

```
messages.sendMessage = function (roomId, inputEl) {
		var msg = inputEl.val();
		var mid = inputEl.attr('data-mid');

		if (!msg.trim().length) {
			return;
		}

                //For Quill
		try {
			let tmp_msg = JSON.parse(msg);
			if(tmp_msg.hasOwnProperty('ops') && (tmp_msg.ops.length === 1) && tmp_msg.ops[0].hasOwnProperty('insert') && (tmp_msg.ops[0].insert === '\n'))
				return;
		} catch(e) {
			//Regular string
		}

```

**Comment by julianlam** [comment]
Altering core is almost always a bad idea, when it is done for just one plugin.
