### ISSUE TITLE
Chat message editing does not work yet

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-plugin-composer-quill#7]

**Comment by PostMidnight** [comment]
Hi @julianlam this feature is also important for chat, I hope it will be fixed soon. Other than chat, quill plugin is in a great shape.

**Comment by PostMidnight** [comment]
The problem stem from the below code:

With Quill, inputEl.val() contains the quill data, its not empty.
A temporary fix is to remove the "if" condition. A better fix would be to examine the content and find at least one class that relates to quill (note inputEl.val() is not delta but html).

Moving on, the content of the message targeted for editing is sent to the textarea. However, there is no code that triggers Quill to grab the data into its own editor window.

```
messages.prepEdit = function (inputEl, messageId, roomId) {
		socket.emit('modules.chats.getRaw', { mid: messageId, roomId: roomId }, function (err, raw) {
			if (err) {
				return app.alertError(err.message);
			}
			// Populate the input field with the raw message content
			//if (inputEl.val().length === 0) {
				// By setting the `data-mid` attribute, I tell the chat code that I am editing a
				// message, instead of posting a new one.
				inputEl.attr('data-mid', messageId).addClass('editing');
				inputEl.val(raw);
			//}
		});
	};
```

**Comment by julianlam** [comment]
Chat editing works now.
