### ISSUE TITLE
[Enhancement] Use quill-delta-to-html

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-composer-quill#75]
Seems that this package is better in a sense that the development is active.
Furthermore, output may be customized. 
Works better for rtl, although not perfect...

**Comment by julianlam** [comment]
We use this dependency already....

https://github.com/NodeBB/nodebb-plugin-composer-quill/blob/master/package.json#L33
https://github.com/NodeBB/nodebb-plugin-composer-quill/blob/master/lib/migrator.js#L5
