### ISSUE TITLE
Migrator for chat

### ISSUE THREAD

**Issue by PostMidnight** [NodeBB/nodebb-plugin-composer-quill#82]
Hi @julianlam ,
How are the chats being migrated. I have an issue in which some chat messages are showing quill format, and can't find the migration code.
thanks,
JJ.

**Comment by julianlam** [comment]
I don't believe chats are migrated right now, only posts. Are you migrating to or from quill?

**Comment by PostMidnight** [comment]
To quill. So I guess chat messages are translated in real time. I'll dig into this issue and report back

**Comment by PostMidnight** [comment]
Hi @julianlam, 

I realize now that the chats are translated to html and sanitized when received. 

It might be beneficial to save in quill format as well. Let me explain:
Some users (including yours truly) may/are using quill for chat, allowing room participants to format the text a bit, and share emojis, upload images, files etc.
Editing a chat message is a necessary feature. It currently does not work, partly because the content of the chat message is html. Indeed, one may argue that we can feed html to quill and be done with it, however the translation back and forth from delta will (at least in my setup) yield potential formatting and RTL issues. It is quite challenging to fix these with css. 

Please thus consider saving chats in delta format as well, and serving delta to the client when requested.

As for the issue above (" some chat messages are showing quill format"): Per your implementation, the messages were converted from delta and saved as html, I guess the converter failed. I don't know why yet as I cannot reproduce the same.  I do see however that all the faulty messages have one thing in common: they were edited, or at least, attempted to be edited. So something in the edit loop may have caused this issue.

With your permission, I am closing this issue.
