### ISSUE TITLE
quill path problem

### ISSUE THREAD

**Issue by peterchealse** [NodeBB/nodebb-plugin-composer-quill#97]
**version:**  
nodebb 1.12    
nodebb-plugin-composer-quill 1.1.1

**problem:**
File not found! nodebb-plugin-composer-quill/node_modules/quill/dist/quill.bubble.css

I found that quill is not installed in the local path, so it is not found. So is it caused by npm version? or do I miss some other config?

**Comment by julianlam** [comment]
How did you install the quill composer? via npm?

**Comment by peterchealse** [comment]
yes

**Comment by julianlam** [comment]
Where are you seeing this error, in console or in usage of NodeBB? Please attach reproduction steps.

**Comment by peterchealse** [comment]
In console.  I have made a new npm package based on it.

**Comment by julianlam** [comment]
Why? I'd recommend you submit the fix as a pull request instead of forking and republishing the package, but that is just me...
